// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package save

import (
	"time"
)

type Interval struct {
	Person    string
	StartAt   time.Time
	EndBefore time.Time
	Kind      string
}

type Person struct {
	Handle string
}
