// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package save

import (
	"time"
)

type Event struct {
	Person   string
	Schedule string
	Kind     string
	At       time.Time
}

type Interval struct {
	Person    string
	Schedule  string
	StartAt   time.Time
	EndBefore time.Time
	Kind      string
}

type Schedule struct {
	Name string
}
