// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package save

import (
	"context"
	"time"
)

const addInterval = `-- name: AddInterval :exec
INSERT INTO interval(person, schedule, start_at, end_before, kind)
VALUES (?, ?, ?, ?, ?)
`

type AddIntervalParams struct {
	Person    string
	Schedule  string
	StartAt   time.Time
	EndBefore time.Time
	Kind      string
}

func (q *Queries) AddInterval(ctx context.Context, arg AddIntervalParams) error {
	_, err := q.db.ExecContext(ctx, addInterval,
		arg.Person,
		arg.Schedule,
		arg.StartAt,
		arg.EndBefore,
		arg.Kind,
	)
	return err
}

const addPerson = `-- name: AddPerson :exec
INSERT INTO person(handle) VALUES (?)
`

func (q *Queries) AddPerson(ctx context.Context, handle string) error {
	_, err := q.db.ExecContext(ctx, addPerson, handle)
	return err
}

const addSchedule = `-- name: AddSchedule :exec
INSERT INTO schedule(name) VALUES (?)
`

func (q *Queries) AddSchedule(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, addSchedule, name)
	return err
}

const participate = `-- name: Participate :exec
INSERT INTO participate(person, schedule, kind, at)
VALUES (?, ?, ?, ?)
`

type ParticipateParams struct {
	Person   string
	Schedule string
	Kind     string
	At       time.Time
}

func (q *Queries) Participate(ctx context.Context, arg ParticipateParams) error {
	_, err := q.db.ExecContext(ctx, participate,
		arg.Person,
		arg.Schedule,
		arg.Kind,
		arg.At,
	)
	return err
}
