// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package save

import (
	"context"
	"time"
)

const addPerson = `-- name: AddPerson :exec
INSERT INTO person(handle) VALUES (?)
`

func (q *Queries) AddPerson(ctx context.Context, handle string) error {
	_, err := q.db.ExecContext(ctx, addPerson, handle)
	return err
}

const addShift = `-- name: AddShift :exec
INSERT INTO shift(person, start_at, end_before)
VALUES (?,?,?)
`

type AddShiftParams struct {
	Person    string
	StartAt   time.Time
	EndBefore time.Time
}

func (q *Queries) AddShift(ctx context.Context, arg AddShiftParams) error {
	_, err := q.db.ExecContext(ctx, addShift, arg.Person, arg.StartAt, arg.EndBefore)
	return err
}
